/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTitle: typeof import('./src/components/common/AppTitle.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    IconAccountCircle: typeof import('./src/components/icons/IconAccountCircle.vue')['default']
    IconAdd: typeof import('./src/components/icons/IconAdd.vue')['default']
    IconAgender: typeof import('./src/components/icons/IconAgender.vue')['default']
    IconChat: typeof import('./src/components/icons/IconChat.vue')['default']
    IconEmail: typeof import('./src/components/icons/IconEmail.vue')['default']
    IconFemale: typeof import('./src/components/icons/IconFemale.vue')['default']
    IconGroup: typeof import('./src/components/icons/IconGroup.vue')['default']
    IconKey: typeof import('./src/components/icons/IconKey.vue')['default']
    IconLock: typeof import('./src/components/icons/IconLock.vue')['default']
    IconMale: typeof import('./src/components/icons/IconMale.vue')['default']
    IconNorthEast: typeof import('./src/components/icons/IconNorthEast.vue')['default']
    IconNotificationOff: typeof import('./src/components/icons/IconNotificationOff.vue')['default']
    IconPerson: typeof import('./src/components/icons/IconPerson.vue')['default']
    IconPersonFill: typeof import('./src/components/icons/IconPersonFill.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconSettings: typeof import('./src/components/icons/IconSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserSexIcon: typeof import('./src/components/user/UserSexIcon.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
